fix: avoid loading types node
amplitude/Amplitude-TypeScript pull request #301
Opened 2022-12-23 05:21 UTC by liuyang1520

### Summary
- fix: avoid loading types node

https://github.com/amplitude/Amplitude-TypeScript/issues/281, update the `scheduled` seems working for my local.

Add `void` to `appStateChangeHandler` for fixing the building error:
```
@amplitude/analytics-react-native: src/react-native-client.ts:83:5 - error TS2322: Type 'void' is not assignable to type 'NativeEventSubscription | undefined'.
@amplitude/analytics-react-native: 83     this.appStateChangeHandler = AppState.addEventListener('change', this.handleAppStateChange);
@amplitude/analytics-react-native:        ~~~~~~~~~~~~~~~~~~~~~~~~~~
@amplitude/analytics-react-native: Found 1 error.
```

### Checklist

* [x] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-TypeScript/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:  No

2022-12-23 09:55 UTC, falconandy requested changes
1. I do not have the build error with `appStateChangeHandler`. Could you please check you have fresh `node_modules`? `package.json`/`yarn.lock` were changed recently

> And ideally, a CI job should ensure that @amplitude/analytics-browser stays free from references to @types/node as that's not the first time a similar issue happens

2.  Can we check if `/// <reference types="node" />` line exists in `lib` folders of non-Node packages?

2022-12-23 18:11 UTC, liuyang1520 commented
> 1. I do not have the build error with `appStateChangeHandler`. Could you please check you have fresh `node_modules`? `package.json`/`yarn.lock` were changed recently
> 
> > And ideally, a CI job should ensure that @amplitude/analytics-browser stays free from references to @types/node as that's not the first time a similar issue happens
> 
> 2. Can we check if `/// <reference types="node" />` line exists in `lib` folders of non-Node packages?

@falconandy Thanks for reviewing!

I don't have other local changes. ![image](https://user-images.githubusercontent.com/8689754/209384739-e8da1da1-0ae8-42f7-b0d6-5aff1a6acfc6.png)

I remove my local `node_modules`, then `yarn install`, and `yarn build`, the issue was gone. Will revert that type change.

I checked the `/// <reference types="node" />` in my local `packages` folder after building, there is no line. I think after we change the `scheduled` to private, it won't load the node type anyways. Let me know if I miss anything.

2022-12-23 18:40 UTC, qingzhuozhen approved these changes

2022-12-24 05:32 UTC, falconandy commented
@liuyang1520 
I mean can we add new check to prevent unexpected dependence:
If `/// <reference types="node" />` line doesn't exist in `lib` folders of non-Node packages - it's ok, we have no unexpected dependence from Node
If `/// <reference types="node" />` line  exists in `lib` folders of non-Node packages - unexpected Node dependence exists and should be fixed

2023-01-04 20:05 UTC, liuyang1520 commented
> @liuyang1520 I mean can we add new check to prevent unexpected dependence: If `/// <reference types="node" />` line doesn't exist in `lib` folders of non-Node packages - it's ok, we have no unexpected dependence from Node If `/// <reference types="node" />` line exists in `lib` folders of non-Node packages - unexpected Node dependence exists and should be fixed

@falconandy , I see! Let me see how I can add a check in the github workflow for preventing this. To clarify, I think we should grep the `/// <reference types="node" />` in my local packages folder after building, I notice you mentioned the `lib` folder, but I cannot find it, is there anything I am missing?

2023-01-06 05:53 UTC, falconandy commented
@liuyang1520 
maybe `lib` folder is created after `build` command
![image](https://user-images.githubusercontent.com/9509929/210938929-3309952f-48f0-4731-ae98-065327deb9b0.png)

2023-01-06 18:51 UTC, liuyang1520 commented
> @liuyang1520 maybe `lib` folder is created after `build` command ![image](https://user-images.githubusercontent.com/9509929/210938929-3309952f-48f0-4731-ae98-065327deb9b0.png)

I can see the `lib` folder now, will try to add the checker for this. Thank you!

2023-01-10 19:27 UTC, liuyang1520 commented
@falconandy , @kevinpagtakhan , will merge this first to solve the issue and work on the automatic check in separate PR

2023-01-10 19:32 UTC, merged